apiVersion: apps/v1
kind: Deployment
metadata:
  name: gke-flask-example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - name: hello-app
        image: europe-west2-docker.pkg.dev/dft-dst-prt-connectivitymetric/gke-flask-example/gke_flask_example:latest
        ports:
        - containerPort: 8080
        env:
          - name: PORT
            value: "8080"
---